name: GodMode
main: com.msm595.GodMode.GodMode
version: 0.3.0
author: Msm595
description: >
             Lightweight godmode plugin with optional permissions.
commands:
  god:
    description: Toggle godmode.
    usage: |
           /<command> [player] [-noFire]
           Example: /<command> - toogles godmode on yourself
           Example: /<command> -noFire - toggles nofire
           Example: /<command> Bukkit - toggles godmode on Bukkit
           Example: /<command> Bukkit -noFire - toggles nofire on Bukkit
  godmode:
    description: Toggle godmode.
    usage: |
           /<command> [player] [-noFire]
           Example: /<command> - toogles godmode on yourself
           Example: /<command> -noFire - toggles nofire
           Example: /<command> Bukkit - toggles godmode on Bukkit
           Example: /<command> Bukkit -noFire - toggles nofire on Bukkit