name: GodMode
main: com.msm595.GodMode.GodMode
version: 0.2.0
author: Msm595
description: >
             Lightweight godmode plugin with optional permissions.
commands:
  god:
    description: Toggle godmode.
    usage: |
           /<command> [player]
           Example: /<command> - toogles godmode on yourself
           Example: /<command> Bukkit - toggles godmode on Bukkit
  godmode:
    description: Toggle godmode.
    usage: |
           /<command> [player]
           Example: /<command> - toogles godmode on yourself
           Example: /<command> Bukkit - toggles godmode on Bukkit